version: '3.7'
services:
  zabbix-db:
    image: mysql:5.7
    networks:
      - vpcstack
    ports:
     - "3306:3306"
    #command: 
    # - mysqld
    # - --character-set-server=utf8
    # - --collation-server=utf8_bin
    # - --default-authentication-plugin=mysql_native_password    
    volumes:
      - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
      #- ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      #- ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      #- ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      #- ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      #- ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      #- ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      #- ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      #- snmptraps:/var/lib/zabbix/snmptraps:rw
    #env_file:
    # - .env_db_mysql
    #secrets:
    # - MYSQL_USER
    # - MYSQL_PASSWORD
    # - MYSQL_ROOT_PASSWORD

    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    #  POSTGRES_DB: "zabbix"
    #  POSTGRES_USER: "zabbix"
    #  POSTGRES_PASSWORD: "zabbix"

  #db_data_mysql:
  #  image: busybox
  #  volumes:
  #    - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.4-latest
    networks:
      - vpcstack
    restart: always  
    #ports:
    # - "10051:10051"
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    #  DB_SERVER_HOST: "zabbix-db"
    #  POSTGRES_USER: "zabbix"
    #  POSTGRES_PASSWORD: "zabbix"
    #  POSTGRES_DB: "zabbix"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    depends_on:
      - "zabbix-db"
    links:
      - "zabbix-db"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-5.4-latest
    networks:
      - vpcstack
    #secrets:
    # - MYSQL_USER
    # - MYSQL_PASSWORD
    # - MYSQL_ROOT_PASSWORD
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
      PH P_TZ: "America/Sao_Paulo"
      #DB_SERVER_HOST: "zabbix-db"
      #POSTGRES_USER: "zabbix"
      #POSTGRES_PASSWORD: "zabbix"
      #POSTGRES_DB: "zabbix"
      #ZBX_SERVER_HOST: "zabbix-server"
      #PHP_TZ: "Asia/Tokyo"
    depends_on:
      - "zabbix-db"
      - "zabbix-server"
    links:
      - "zabbix-db"
      - "zabbix-server"
    ports:
      - "80:8080"

  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-5.4-latest
    networks:
      - vpcstack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    environment:
      ZBX_HOSTNAME: "zabbix-grafanaa_zabbix-server_1"
      ZBX_SERVER_HOST: "zabbix-grafanaa_zabbix-server_1"

    depends_on:    
      - "zabbix-server"
    links:    
      - "zabbix-server"


  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-5.4-latest
    networks:
      - vpcstack
    profiles:
      - full
      - all
    ports:
      - "162:1162/udp"
    volumes:
      - snmptraps:/var/lib/zabbix/snmptraps:rw
    deploy:
     resources:
      limits:
        cpus: '0.5'
        memory: 256M
      reservations:
        cpus: '0.25'
        memory: 128M
    #networks:
    # zbx_net_frontend:
    #  aliases:
    #   - zabbix-snmptraps
    # zbx_net_backend:
    #stop_grace_period: 5s
    #labels:
    #com.zabbix.description: "Zabbix snmptraps"
    #com.zabbix.company: "Zabbix LLC"
    #com.zabbix.component: "snmptraps"
    #com.zabbix.os: "ubuntu"


  grafana:
    image: bitnami/grafana-image-renderer
    container_name: grafana
    links:
      - zabbix-server
      - zabbix-db
    #user: '104'
    #command:
    #  - ls -la /usr/share/grafana/bin/
    #  - /usr/share/grafana/bin/grafana-cli
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,raintank-worldping-app
    volumes:
      - ./zbx_env/grafana-config:/etc/grafana:rw
      - ./zbx_env/grafana-data:/var/lib/grafana:rw
      - ./zbx_env/grafana-home:/usr/share/grafana:rw
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - zabbix-web
      - zabbix-server
    networks:
      - vpcstack

volumes:
  snmptraps:
  grafana-config:
  grafana-data:
  grafana-home:

networks:
  vpcstack:

secrets:
  MYSQL_USER:
    file: ./.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./.MYSQL_ROOT_PASSWORD
